# Generated by Django 5.2.11 on 2026-02-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
